name: mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # Add high-resolution artwork files for your app in assets/images.
    # Once available, include them here:
    # - assets/images/monsters.png
    # - assets/images/journey_cards.png
    # - assets/images/mystery_cards.png
